### ISSUE TITLE
Req Permission to use figures

### ISSUE THREAD

**Issue by saikamat** [adl1995/adl1995.github.io#1]
Hi Adeel,

May I have your permission to use the activation function figures in my research paper? I'll cite your repository.

-Sai

**Comment by adl1995** [comment]
Hi Sai,

Sure, go ahead! You can also have a look at the source code (https://github.com/adl1995/adl1995.github.io/blob/master/notebooks/Activation%20functions.ipynb) if you decide to tweak some values.

If you make your research paper public, I'll be happy to read it.
